language: c

matrix:
  include:

    # ###### Fedora Linux ###################################################

    # ====== Fedora 25 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:25" VARIANT="fedora"

    # ====== Fedora 27 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:27" VARIANT="fedora"

    # ====== Fedora 29 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:29" VARIANT="fedora"

    # ====== Fedora Rawhide =================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:rawhide" VARIANT="fedora"


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo docker run -d --name ubuntu-test -v $(pwd):/travis -w /travis $DOCKER tail -f /dev/null
       sudo docker ps
    elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
       brew update
       # brew install cmake
    fi


install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       if [ "$VARIANT" = "ubuntu" ] ; then
          sudo docker exec -t ubuntu-test bash -c "apt-get update"
          sudo docker exec -t ubuntu-test bash -c "apt-get install -y gcc make"
       elif [ "$VARIANT" = "fedora" ] ; then
          sudo docker exec -t ubuntu-test bash -c "dnf install -y curl wget gcc make kmod patch bash tar git-core bzip2 xz findutils gzip m4 perl-interpreter perl-Carp perl-devel perl-generators make diffutils gawk gcc binutils redhat-rpm-config hmaccalc bison flex net-tools hostname bc elfutils-devel sparse rpm-build elfutils openssl openssl-devel pesign"
       fi
    fi


script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       travis_wait 300 sudo docker exec -t ubuntu-test bash -c "make srpm rpm"
    fi
