#!/bin/bash -e

UPSTREAM_KERNEL_REPOSITORY=`cat upstream | sed -e 's/@.*$//g'`
UPSTREAM_KERNEL_BRANCH=`cat upstream | sed -e 's/^.*@//g'`


if [ ! -e upstream-kernel ] ; then
   git clone "$UPSTREAM_KERNEL_REPOSITORY" upstream-kernel
fi
cd upstream-kernel
git checkout "$UPSTREAM_KERNEL_BRANCH" .

cat ../sources | (
   while read checksum url ; do
      file=`echo "$url" | sed -e "s/.*\///g"`
      if [ ! -e $file ] ; then
         echo "Fetching $file from $url ..."
         curl "$url" >$file.tmp
         mv $file.tmp $file
      fi
      if [ "`sha256sum $file | awk '{ print $1 }'`" != "$checksum" ] ; then
         echo "SHA-256 sum of the downloaded $file does not match the one from 'sources' file!"
         echo "Local copy: `sha256sum $file | awk '{ print $1 }'`"
         echo "In sources: $checksum"
         exit 1
      fi
   done
)
cd ..

echo "done!"
